"""Renders kafe/status_codes.py's full 213-code catalog (plus code "0000") into a Bikeshed include,
consumed by kafe/request.bs's error-handling section. Unlike every other
generator in this repo, this one's source is a hand-transcribed Python data
file, not an XSD -- see kafe/status_codes.py's own module docstring for why.

Run from the repository root::

    python -m kafe.generate_status_codes_docs
"""
from __future__ import annotations

from pathlib import Path

from kafe.status_codes import RANGE_ORDER, STATUS_CODES, codes_in_range

ROOT = Path(__file__).resolve().parent
OUTPUT_PATH = ROOT / "generated" / "status-codes.include.bs"


def _esc(value: str) -> str:
    return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _slug(text: str) -> str:
    return text.lower().replace(" ", "-").replace("/", "-")


def main() -> None:
    lines: list[str] = [
        "<!-- Generated by kafe/generate_status_codes_docs.py from "
        "kafe/status_codes.py. Do not edit by hand. -->",
        "",
        '<h2 id="status-codes">Status and error codes</h2>',
        "",
        "<p>Every status code KaFE-RM's <code>ValidierungsergebnisListe</code> "
        "may report, grouped by the numeric range the official handbook itself "
        "uses.</p>",
        "",
    ]

    # "0000" (OK) lives outside RANGE_ORDER's 7 numeric ranges entirely (Task 2's
    # own ruling) -- render it as its own leading section rather than silently
    # dropping it, since the loop below only ever reaches codes inside the 7
    # named ranges.
    ok_code = STATUS_CODES["0000"]
    lines.append('<h3 id="status-0000-ok">0000 - OK</h3>')
    lines.append("")
    lines.append('<table class="complex data longlastcol dictionary">')
    lines.append("  <thead><tr><th>Code<th>Message</tr></thead>")
    lines.append("  <tbody>")
    lines.append(
        f"    <tr><td><code>{_esc(ok_code.code)}</code>"
        f'<td class="long">{_esc(ok_code.message)}</tr>'
    )
    lines.append("  </tbody>")
    lines.append("</table>")
    lines.append("")

    for range_label in RANGE_ORDER:
        anchor = f"status-{_slug(range_label)}"
        lines.append(f'<h3 id="{anchor}">{_esc(range_label)}</h3>')
        lines.append("")
        lines.append('<table class="complex data longlastcol dictionary">')
        lines.append("  <thead><tr><th>Code<th>Message</tr></thead>")
        lines.append("  <tbody>")
        for status_code in codes_in_range(range_label):
            lines.append(
                f"    <tr><td><code>{_esc(status_code.code)}</code>"
                f'<td class="long">{_esc(status_code.message)}</tr>'
            )
        lines.append("  </tbody>")
        lines.append("</table>")
        lines.append("")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
