"""Builds kafe/generated/rm.include.bs from the real KaFE-RM (submission
receipt) XSD.

Reuses engine.xsd_model.XsdModel (the same XSD-to-facts layer the Request-side
Excel/data-dictionary pipeline uses) so the receipt document's field
descriptions, types, and requiredness are pulled from kafe-rm.xsd's own
xs:documentation, never hand-typed. Unlike the Request side, there is no Excel
template to build here -- this script only renders a Bikeshed include.

Run from the repository root::

    python -m kafe.generate_rm_docs
"""

from __future__ import annotations

from pathlib import Path

from engine.xsd_model import Field, XsdModel

ROOT = Path(__file__).resolve().parent
XSD_PATH = ROOT / "kafe-rm.xsd"
OUTPUT_PATH = ROOT / "generated" / "rm.include.bs"

# Root type of a single Antrag (per-application) entry within the KAFE-RM
# receipt -- confirmed by reading kafe/kafe-rm.xsd directly: Antrag_CType is
# an AntragId attribute plus a choice of RegistrierNr (on acceptance) or
# ValidierungsergebnisListe (on rejection).
RM_TYPE = "Antrag_CType"

# Section name -> ordered list of (kind, ref) to resolve. kind is "attr",
# "elem", or "path" (a list of names to walk, needed to reach the fields
# nested under ValidierungsergebnisListe/Validierungsergebnis).
SECTIONS: list[tuple[str, list[tuple[str, object]]]] = [
    ("Per-application response", [
        ("attr", "AntragId"),
        ("elem", "RegistrierNr"),
    ]),
    ("Validation result (on rejection)", [
        ("path", ["ValidierungsergebnisListe", "Validierungsergebnis", "StatusCode"]),
        ("path", ["ValidierungsergebnisListe", "Validierungsergebnis", "Hinweis"]),
    ]),
]


def _resolve(model: XsdModel, kind: str, ref) -> Field:
    if kind == "attr":
        return model.attr(RM_TYPE, ref)
    if kind == "elem":
        return model.elem(RM_TYPE, ref)
    if kind == "path":
        return model.path(RM_TYPE, ref)
    raise ValueError(f"unknown field kind {kind!r}")


def _slug(name: str) -> str:
    return name.lower().replace(".", "-").replace(" ", "-")


def _esc(value: str) -> str:
    return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _render_section(name: str, fields: list[tuple[str, object]], model: XsdModel) -> list[str]:
    anchor = _slug(name)
    lines = [f'<h3 id="{anchor}">{_esc(name)}</h3>', ""]
    lines.append('<table class="complex data longlastcol dictionary">')
    lines.append("  <colgroup>")
    lines.append('    <col style="width:18%">')
    lines.append('    <col style="width:12%">')
    lines.append('    <col style="width:20%">')
    lines.append('    <col style="width:50%">')
    lines.append("  </colgroup>")
    lines.append(
        '  <thead><tr><th>Field<th class="col-req">Requiredness'
        "<th>Type / Allowed values<th>Description</tr></thead>"
    )
    lines.append("  <tbody>")
    for kind, ref in fields:
        field = _resolve(model, kind, ref)
        requiredness = "Required" if field.required else "Optional"
        lines.append(
            f"    <tr><td><code>{_esc(field.name)}</code>"
            f'<td class="col-req">{requiredness}'
            f"<td>{_esc(field.type_display)}"
            f'<td class="long">{_esc(field.description)}</tr>'
        )
    lines.append("  </tbody>")
    lines.append("</table>")
    lines.append("")
    return lines


def main() -> None:
    model = XsdModel(str(XSD_PATH))

    lines: list[str] = [
        "<!-- Generated by kafe/generate_rm_docs.py from "
        f"{XSD_PATH.name}. Do not edit by hand. -->",
        "",
        '<h2 id="rm-fields">Submission receipt fields</h2>',
        "",
        "<p>A KAFE-RM receipt batches one <code>Antrag</code> entry per "
        "submitted <code>Erstattungsantrag</code>, correlated back to the "
        "submitter's own <code>AntragId</code>. Each entry carries either a "
        "<code>RegistrierNr</code> (on acceptance) or a "
        "<code>ValidierungsergebnisListe</code> (on rejection), never both. "
        "Fields below are grouped by where they appear in that structure.</p>",
        "",
    ]
    for name, fields in SECTIONS:
        lines.extend(_render_section(name, fields, model))

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
